<?php
/**
 * TL_ROOT/system/modules/module_richtext/languages/ru/modules.php 
 * 
 * TYPOlight extension: module_richtext 0.1.0 stable 
 * Russisch translation file 
 * 
 * Copyright : &copy; 2008 Felix Pfeiffer : Neue Medien 
 * License   : LGPL 
 * Author    : Felix Pfeiffer (felixpfeiffer), http://www.felixpfeiffer.de 
 * Translator: Dmitry Kuznetsov (kuzmich), http://on.freedom-vrn.ru 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['FMD']['module_richtext']['0'] = "RichText";
$GLOBALS['TL_LANG']['FMD']['module_richtext']['1'] = "Заполнение с использованием tinyMCE.";
 
?>
