<?php
/**
 * TL_ROOT/system/modules/table4ward/languages/nl/tl_content.php 
 * 
 * Contao extension: table4ward 1.0.1 stable 
 * Dutch translation file 
 * 
 * Copyright : 4ward.media 
 * License   : LGPL 
 * Author    : Christoph Wiechert (Psi), http://www.4wardmedia.de 
 * Translator: Just Schimmelpenninck (justs) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_content']['dblclickHint'] = "Dubbelklik cellen om ze te veranderen m.b.v. tinyMCE.";
$GLOBALS['TL_LANG']['tl_content']['rnew']['0'] = "Nieuwe rij";
$GLOBALS['TL_LANG']['tl_content']['rnew']['1'] = "Maak een nieuwe rij";
$GLOBALS['TL_LANG']['tl_content']['cnew']['0'] = "Nieuwe kolom";
$GLOBALS['TL_LANG']['tl_content']['cnew']['1'] = "Maak een nieuwe kolom";
 
?>
