<?php
/**
 * TL_ROOT/system/modules/module_richtext/languages/sr/tl_module.php 
 * 
 * TYPOlight extension: module_richtext 0.1.0 stable 
 * Serbian translation file 
 * 
 * Copyright : &copy; 2008 Felix Pfeiffer : Neue Medien 
 * License   : LGPL 
 * Author    : Felix Pfeiffer (felixpfeiffer), http://www.felixpfeiffer.de 
 * Translator: Janos Guljas (Janos), http://www.janos.in.rs 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['richtext']['0'] = "Текст";
$GLOBALS['TL_LANG']['tl_module']['richtext']['1'] = "Унесите текст (можете користити HTML тагове).";
 
?>
